#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUNNER_SOURCE="${RUNNER_ENTITLEMENTS_SOURCE:-$ROOT_DIR/scripts/ios/runner-entitlements.plist}"
TROLLSTORE_SOURCE="${TROLLSTORE_ENTITLEMENTS_SOURCE:-$ROOT_DIR/scripts/ios/trollstore-entitlements.plist}"

usage() {
  echo "Usage: sync_entitlements.sh --trollstore <resolved-entitlements.plist>"
  echo "       sync_entitlements.sh --runner-files"
}

MODE=''
DEST_FILE=''
case "${1:-}" in
  --runner-files)
    if [[ "$#" -ne 1 ]]; then
      usage >&2
      exit 2
    fi
    MODE='runner-files'
    ;;
  --trollstore)
    if [[ "$#" -ne 2 ]]; then
      usage >&2
      exit 2
    fi
    MODE='trollstore'
    DEST_FILE="$2"
    ;;
  -h|--help)
    if [[ "$#" -ne 1 ]]; then
      usage >&2
      exit 2
    fi
    usage
    exit 0
    ;;
  *)
    echo "An explicit entitlement context is required" >&2
    usage >&2
    exit 2
    ;;
esac

write_generated_mirror() {
  local source="$1"
  local destination="$2"
  mkdir -p "$(dirname "$destination")"
  sed \
    's/Keep this as the only manually maintained Xcode Runner entitlement source\./Generated from scripts\/ios\/runner-entitlements.plist. Do not edit this file directly./' \
    "$source" >"$destination"
  plutil -lint "$destination"
  echo "generated_entitlement=$destination"
}

if [[ "$MODE" == 'runner-files' ]]; then
  if [[ ! -f "$RUNNER_SOURCE" ]]; then
    echo "Missing Xcode Runner entitlement source: $RUNNER_SOURCE" >&2
    exit 1
  fi
  plutil -lint "$RUNNER_SOURCE"
  echo "runner_entitlement_source=$RUNNER_SOURCE"
  write_generated_mirror "$RUNNER_SOURCE" "$ROOT_DIR/ios/Runner/DebugProfile.entitlements"
  write_generated_mirror "$RUNNER_SOURCE" "$ROOT_DIR/ios/Runner/Release.entitlements"
else
  if [[ ! -f "$TROLLSTORE_SOURCE" ]]; then
    echo "Missing TrollStore entitlement source: $TROLLSTORE_SOURCE" >&2
    exit 1
  fi
  plutil -lint "$TROLLSTORE_SOURCE"
  echo "trollstore_entitlement_source=$TROLLSTORE_SOURCE"
  mkdir -p "$(dirname "$DEST_FILE")"
  cp "$TROLLSTORE_SOURCE" "$DEST_FILE"
  plutil -lint "$DEST_FILE"
  echo "resolved_entitlement=$DEST_FILE"
fi
