#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SOURCE_FILE="${ENTITLEMENTS_SOURCE:-$ROOT_DIR/scripts/ios/trollstore-entitlements.plist}"

usage() {
  echo "Usage: sync_entitlements.sh [resolved-entitlements.plist]"
  echo "       sync_entitlements.sh --runner-files"
}

if [[ "${1:-}" == "--runner-files" ]]; then
  MODE='runner-files'
  DEST_FILE=''
elif [[ "${1:-}" == '-h' || "${1:-}" == '--help' ]]; then
  usage
  exit 0
else
  MODE='resolved'
  DEST_FILE="${1:-${RUNNER_TEMP:-$ROOT_DIR/build/ios}/resolved-entitlements.plist}"
fi

if [[ ! -f "$SOURCE_FILE" ]]; then
  echo "Missing entitlement source: $SOURCE_FILE" >&2
  exit 1
fi

plutil -lint "$SOURCE_FILE"
echo "entitlement_source=$SOURCE_FILE"

write_generated_mirror() {
  local destination="$1"
  mkdir -p "$(dirname "$destination")"
  sed \
    's/Keep this as the only manually maintained entitlement source\./Generated from scripts\/ios\/trollstore-entitlements.plist. Do not edit this file directly./' \
    "$SOURCE_FILE" >"$destination"
  plutil -lint "$destination"
  echo "generated_entitlement=$destination"
}

if [[ "$MODE" == 'runner-files' ]]; then
  write_generated_mirror "$ROOT_DIR/ios/Runner/DebugProfile.entitlements"
  write_generated_mirror "$ROOT_DIR/ios/Runner/Release.entitlements"
else
  mkdir -p "$(dirname "$DEST_FILE")"
  cp "$SOURCE_FILE" "$DEST_FILE"
  plutil -lint "$DEST_FILE"
  echo "resolved_entitlement=$DEST_FILE"
fi
